// Client/src/views/login.jsx
import { useState } from 'react';
import axios from 'axios';
import { useNavigate } from 'react-router-dom';

function Login() {
  const [username, setUsername] = useState(localStorage.getItem('loggedInUsername') || '');
  const [password, setPassword] = useState('');
  const navigate = useNavigate();

  const login = async (event) => {
    event.preventDefault(); // Previene el comportamiento predeterminado del formulario

    try {
      const response = await axios.post('http://localhost:3333/users/login', {
        username,
        password,
      });

      if (response.status === 200) {
        localStorage.setItem('loggedInUsername', username); // Almacenar el nombre de usuario en el localStorage
        navigate('/profile'); // Navegar al perfil
      }
    } catch (error) {
      console.error('Error al iniciar sesión:', error);
    }
  };

  return (
    <div className="flex justify-center items-center h-screen">
    <form className="bg-gray-100 p-6 rounded-md shadow-md" onSubmit={login}>
      <h2 className="text-2xl font-semibold mb-4">Iniciar Sesión</h2>
      <div className="mb-4">
        <label htmlFor="username" className="block text-sm font-medium text-gray-600">
          Nombre de Usuario
        </label>
        <input
          type="text"
          id="username"
          value={username}
          onChange={(e) => setUsername(e.target.value)}
          placeholder="Nombre de Usuario"
          className="mt-1 p-2 w-full border rounded-md"
          required
        />
      </div>
      <div className="mb-4">
        <label htmlFor="password" className="block text-sm font-medium text-gray-600">
          Contraseña
        </label>
        <input
          type="password"
          id="password"
          value={password}
          onChange={(e) => setPassword(e.target.value)}
          placeholder="Contraseña"
          className="mt-1 p-2 w-full border rounded-md"
          required
        />
      </div>
      <p className="text-gray-600 mb-2">Usuario: user | Contraseña: 12345</p>
      <button
        type="submit"
        className="bg-blue-600 text-white py-2 px-4 rounded-md hover:bg-blue-700 focus:outline-none focus:ring focus:border-blue-300"
      >
        Ingresar
      </button>
      <p className="mt-3 text-sm">
        ¿No tienes una cuenta? <a href="/signup" className="text-blue-600">Regístrate</a>
      </p>
    </form>
  </div>
  );
}

export default Login;

// Client/src/views/login.vue
<template>
    <div class="login-form-container">
      <form class="login-form" @submit.prevent="login">
        <h2>Iniciar Sesión</h2>
        <div class="form-group">
          <label for="username">Nombre de Usuario</label>
          <input
            type="text"
            id="username"
            v-model="username"
            placeholder="Nombre de Usuario"
            required
          />
        </div>
        <div class="form-group">
          <label for="password">Contraseña</label>
          <input
            type="password"
            id="password"
            v-model="password"
            placeholder="Contraseña"
            required
          />
        </div>
        <p>usuario: user pass: 12345</p>
        <button type="submit">Ingresar</button>
      </form>
    </div>
  </template>
  
  <script>
  import axios from 'axios';

export default {
  data() {
    return {
      username: localStorage.getItem('loggedInUsername'),
      password: '',
    userData: {},
    isPasswordShown: false
    };
  },
  methods: {
    async login() {
      try {
        const response = await axios.post('http://localhost:3333/users/login', {
  username: this.username,
  password: this.password
});
if (response.status === 200) {
  localStorage.setItem('loggedInUsername', this.username); // Almacenar el nombre de usuario en el localStorage
  this.$router.push('/profile'); 
}
        
        console.log('Usuario logueado:', response.data);
        this.$router.push('/profile'); 
      } catch (error) {
        console.error('Error al iniciar sesión:', error);
      }
    }
  }
};
  </script>
  
  <style scoped>
  .login-form-container {
    display: flex;
    justify-content: center;
    align-items: center;
    height: 80vh;
  }
  
  .login-form {
    width: 300px;
    padding: 20px;
    background-color: #f5f5f5;
    border-radius: 10px;
    box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
  }
  
  h2 {
    text-align: center;
  }
  
  .form-group {
    margin-bottom: 15px;
  }
  
  label {
    font-weight: bold;
    display: block;
    margin-bottom: 5px;
  }
  
  input[type="text"],
  input[type="password"] {
    width: 100%;
    padding: 10px;
    border: 1px solid #ccc;
    border-radius: 5px;
  }
  
  button {
    width: 100%;
    padding: 10px;
    background-color: #0c7175;
    color: white;
    border: none;
    border-radius: 5px;
    cursor: pointer;
  }
  
  button:hover {
    background-color: #005658;
  }
  </style>
