// Client/src/components/AppHeader.jsx
import  { useState, useEffect } from 'react';
import { Link, useNavigate, useLocation } from 'react-router-dom';
import logo from '../assets/logo-curseek.png'; // Asegúrate de que la ruta al logo es correcta

function AppHeader() {
  const [loggedInUsername, setLoggedInUsername] = useState(localStorage.getItem('loggedInUsername'));
  const navigate = useNavigate();
  const location = useLocation();

  useEffect(() => {
    // Cada vez que cambia la ubicación (ruta), actualiza el estado
    setLoggedInUsername(localStorage.getItem('loggedInUsername'));
  }, [location]); // Dependencia del efecto en la ubicación actual

  const logout = () => {
    localStorage.removeItem('loggedInUsername');
    setLoggedInUsername(null);
    navigate('/login');
  };

  return (
    <div className="bg-white shadow-md">
      <div className="container mx-auto px-4 py-2">
        <div className="flex items-center justify-between">
          <div className="flex items-center text-xl font-semibold text-purple-900">
            <Link to="/">
              <img src={logo} alt="logo curseek" width="220" />
            </Link>
            <Link to="/cursos" className="ml-4 hover:bg-purple-200 px-3 py-1 rounded transition text-lg">Cursos</Link>
          </div>
          <nav className="space-x-4">
            {loggedInUsername ? (
              <>
                <Link to="/profile" className="hover:bg-purple-200 px-3 py-1 rounded transition text-lg font-bold">Mi Perfil</Link>
                <span className="mr-2">{loggedInUsername}</span>
                <button onClick={logout} className="hover:bg-red-200 text-red-700 px-3 py-1 rounded transition text-lg font-bold">Desconectar</button>
              </>
            ) : (
              <Link to="/login" className="hover:bg-purple-200 px-3 py-1 rounded transition text-lg font-bold">Login</Link>
            )}
          </nav>
        </div>
      </div>
    </div>
  );
}

export default AppHeader;

// Client/src/components/AppHeader.vue
<!-- AppHeader.vue -->
<template>
  <div class="bg-white shadow-md">
    <div class="container mx-auto px-4 py-2">
      <div class="flex items-center justify-between">
        <div class="flex items-center text-xl font-semibold text-purple-900">
          <a href="/">
            <img src="../assets/logo-curseek.png" alt="logo curseek" width="220">
          </a>
          <router-link to="/cursos" class="ml-4 hover:bg-purple-200 px-3 py-1 rounded transition text-lg">Cursos</router-link>
        </div>
        <nav class="space-x-4">
    <div v-if="loggedInUsername">
      <router-link to="/profile" class="hover:bg-purple-200 px-3 py-1 rounded transition text-lg font-bold">Mi Perfil</router-link>
      <span class="mr-2">{{ loggedInUsername }}</span>
      <button @click="logout" class="hover:bg-red-200 text-red-700 px-3 py-1 rounded transition text-lg font-bold">Desconectar</button>
    </div>
    <router-link v-else to="/login" class="hover:bg-purple-200 px-3 py-1 rounded transition text-lg font-bold">Login</router-link>
  </nav>
      </div>
    </div>
  </div>
</template>

  
<script>
export default {
  name: "AppHeader",
  data() {
    return {
      loggedInUsername: localStorage.getItem('loggedInUsername')
    };
  },
  watch: {
    
    '$route': function() {
      this.loggedInUsername = localStorage.getItem('loggedInUsername');
    }
  },
  methods: {
    logout() {
      localStorage.removeItem('loggedInUsername');
      this.loggedInUsername = null;
      this.$router.push('/login');
    }
  }
};
</script>
